In [1]:
import torch

In [4]:
randint = torch.randint(-100,100, (6,))
randint

tensor([ 14, -92,  56,  32, -69, -56])

In [5]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [7]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
input = torch.empty(2,3)
input

tensor([[8.8916e-35, 0.0000e+00, 0.0000e+00],
        [7.0065e-45, 8.8989e-35, 0.0000e+00]])

In [12]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [13]:
linespace = torch.linspace(3, 10, steps=5)
linespace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [15]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [16]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [19]:
a = torch.empty((2,3), dtype=torch.int64)
emptyLike = torch.empty_like(a)
emptyLike

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 4063712724992211300]])